# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true
gems: [jekyll-paginate]
gems: [jekyll-paginate, jekyll-gist]

# Setup
title:            An Explorer's blog
tagline:          'My tech blog'
description:
url:              http://blog.01shobitha.com
baseurl:          /

author:
  name:           'Shobitha'
  url:            https://twitter.com/01shobitha

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/01shobitha
